### ISSUE TITLE
Constant Scanning

### ISSUE THREAD

**Issue by nchezrony** [jishi/node-sonos-http-api#158]
Just installed Raspbian on a RPi2 with Node 5.6.0, but when I start it gives me the following until I quit:
```
pi@raspberrypi:~/sonos $ npm start

> sonos-http-api@0.18.1 start /home/pi/sonos
> node server.js

no settings file found, will only use default settings
info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from eth0
info: relevant IPs 192.168.0.106=null
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
info: notification server listening on port 3500
http server listening on port 5005
no preset file, ignoring...
info: scanning for players in ip 192.168.0.106
info: scanning for players in ip 192.168.0.106
info: scanning for players in ip 192.168.0.106
info: scanning for players in ip 192.168.0.106
```
I have a Playbar, with sub and 2 rears, and a Play:5. The Play:5 is hard-wired, and the rest is wireless.

I tried `{"disableIpDiscovery": true}`, but it did not help. Any ideas on what I'm doing wrong?

**Comment by jishi** [comment]
How is the rpi connected to your network? Could you please post the output from the following commands:

ifconfig
iptables -L
netstat -ntp
route

**Comment by jishi** [comment]
I haven't tested it with 5.6.0 either, it might have something to do with it (I know people have used 5.5.x). If you have the possibility to test that, I would be grateful.

**Comment by nchezrony** [comment]
The RPi is hard-wired as well, headless, using SSH to control it. I'll put the outputs below, but I'll save this image and then try a fresh build using Node 5.5.x to see if it makes a difference.

ifconfig:
```
eth0      Link encap:Ethernet  HWaddr b8:27:eb:c1:ef:89
          inet addr:192.168.0.106  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::d6c7:53f1:9b77:74e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:39510 errors:0 dropped:38 overruns:0 frame:0
          TX packets:5335 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:13365535 (12.7 MiB)  TX bytes:509071 (497.1 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:136 errors:0 dropped:0 overruns:0 frame:0
          TX packets:136 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:11472 (11.2 KiB)  TX bytes:11472 (11.2 KiB)
```
iptables -L
```
modprobe: ERROR: could not insert 'ip_tables': Operation not permitted
iptables v1.4.21: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```
netstat -ntp
```
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0    352 192.168.0.106:22        192.168.0.107:55000     ESTABLISHED -
```
route
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.0.1     0.0.0.0         UG    202    0        0 eth0
192.168.0.0     *               255.255.255.0   U     202    0        0 eth0
```

**Comment by nchezrony** [comment]
Node 5.5.0 made no difference, same result.

**Comment by jishi** [comment]
You nee to run the commands as root or with sudo to begin with.

Is it hardwired to your router? If you connect your computer to the same port, does the Sonos Controller work?

**Comment by nchezrony** [comment]
The RPi is hardwired to the router, as well as the PC. I swapped ports, was able to use the Sonos Controller, no issue, but the same result for your package.

And, my apologies about the commands, you're right, I forgot the sudo:

sudo ifconfig:
```
eth0      Link encap:Ethernet  HWaddr b8:27:eb:c1:ef:89
          inet addr:192.168.0.106  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::d6c7:53f1:9b77:74e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:85807 errors:0 dropped:24 overruns:0 frame:0
          TX packets:64330 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:71926431 (68.5 MiB)  TX bytes:7951572 (7.5 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:263 errors:0 dropped:0 overruns:0 frame:0
          TX packets:263 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:26061 (25.4 KiB)  TX bytes:26061 (25.4 KiB)
```
sudo iptables -L
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```
sudo netstat -ntp
```
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0     96 192.168.0.106:22        192.168.0.107:65515     ESTABLISHED 10917/sshd: pi [pri
```
sudo route
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.0.1     0.0.0.0         UG    202    0        0 eth0
192.168.0.0     *               255.255.255.0   U     202    0        0 eth0
```

**Comment by jishi** [comment]
Hm, very weird. Which distribution and kernel are you running? The only likely cause for this to fail, is that you have something in the network stack that would block multicast traffic but that is not very likely. 

If you have the possibility to hardwire the pi2 directly in one of your Sonos units, we could at least rule out that the router is the culprit. Another option would be to flash your SD-card with the latest minibian and retry the installation (and maybe use node 4.3.0 just to be sure), because that is at least a combination that has been tried and tested.

Other than that, I'm running out of options. The Sonos players should show up using any UPnP testing tool, so if you manage to track down an application for ARM linux, that could also prove useful. There are many people running this with a similar setup as yours, so I'm kind of confused as to why it wouldn't work.

**Comment by nchezrony** [comment]
I tried the latest Raspian with Node 4.3.0, and it still wouldn't work. I then plugged in the RPi with a switch to the Play:5, and lo and behold, everything works!

Not sure what the issue was, but it was definitely something with my router. Thanks for all the support.

**Comment by jishi** [comment]
For future reference, which router are you using?

**Comment by nchezrony** [comment]
It's a TP-Link Archer C7.
